### ISSUE TITLE
negative grades can be entered when creating a new assignment

### ISSUE THREAD

**Issue by Joseph-Richard** [depaul-se-capstone-team-3/student-growth-tracker#132]

**Comment by Joseph-Richard** [comment]
I added this to the score field in db.grade:
requires=IS_FLOAT_IN_RANGE(0, 1000)
Do we have a better idea of what we want to be the maximum possible score, or should i leave it at 1000

**Comment by Larry-Graves** [comment]
I mean, it's pretty much never going to happen that a teacher corrupts a
gradebook with a value like 1000, simply because balancing the class
becomes impossible with numbers that large, but even still, there must be a
function that checks non-negative.

Is it possible to create our own global functions to return true or false
based on an input value?  Like, create a function in db_01_general, and
then use it as the requires= value?

**Comment by Joseph-Richard** [comment]
fixed it. used this instead:
requires=(IS_FLOAT_IN_RANGE(minimum=0)
